ProjectBase/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectBase.Controllers
{
    public class AjaxController : Controller
    {
        ProjectBaseEntities db = new ProjectBaseEntities();
        public ActionResult GroupList(string q, string initValue = "",int page = 0)
        {
            int fromIdx = page > 0 ? (page * 10) : 0;
            int toIdx = page > 0 ? page * 10 : 10;
            var listData = db.Groups.Where(r => 1 == 2);

            if (!string.IsNullOrEmpty(initValue))
            {
                listData = db.Groups
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(initValue) || (initValue == r.Id.ToString()))
                )
                .OrderBy(r => r.Group_Code);
            }
            else
            {
                listData = db.Groups
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(q) || ("[" + r.Group_Code + "] " + r.Group_Description).ToUpper().Contains(q.ToUpper()))
                )
                .OrderBy(r => r.Group_Code);
            }
            var data = listData.Skip(fromIdx)
                .Take(toIdx)
                .Select(r => new { id = r.Id, text = "[" + r.Group_Code + "] " + r.Group_Description })
                .ToList();

            return Json(new { items = data }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult MenuList(string q, string initValue = "", int page = 0)
        {
            int fromIdx = page > 0 ? (page * 10) : 0;
            int toIdx = page > 0 ? page * 10 : 10;
            var listData = db.Menus.Where(r => 1 == 2);

            if (!string.IsNullOrEmpty(initValue))
            {
                listData = db.Menus
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(initValue) || (initValue == r.Id.ToString()))
                )
                .OrderBy(r => r.Id) ;
            }
            else
            {
                listData = db.Menus
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(q) || (r.Menu_Name).ToUpper().Contains(q.ToUpper()))
                )
                .OrderBy(r => r.Id);
            }
            var data = listData.Skip(fromIdx)
                .Take(toIdx)
                .Select(r => new { id = r.Id, text = r.Menu_Name })
                .ToList();

            return Json(new { items = data }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult CustomerList(string q, string initValue = "", int page = 0)
        {
            int fromIdx = page > 0 ? (page * 10) : 0;
            int toIdx = page > 0 ? page * 10 : 10;
            var listData = db.Customers.Where(r => 1 == 2);

            if (!string.IsNullOrEmpty(initValue))
            {
                listData = db.Customers
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(initValue) || (initValue == r.Id.ToString()))
                )
                .OrderBy(r => r.Id);
            }
            else
            {
                listData = db.Customers
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(q) || (r.Code).ToUpper().Contains(q.ToUpper()))
                )
                .OrderBy(r => r.Id);
            }
            var data = listData.Skip(fromIdx)
                .Take(toIdx)
                .Select(r => new { id = r.Id, text = "[" + r.Code + "] " + r.Name })
                .ToList();

            return Json(new { items = data }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ProductList(string q, string initValue = "", int page = 0)
        {
            int fromIdx = page > 0 ? (page * 10) : 0;
            int toIdx = page > 0 ? page * 10 : 10;
            var listData = db.Products.Where(r => 1 == 2);

            if (!string.IsNullOrEmpty(initValue))
            {
                listData = db.Products
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(initValue) || (initValue == r.Id.ToString()))
                )
                .OrderBy(r => r.Id);
            }
            else
            {
                listData = db.Products
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(q) || (r.Product_Name).ToUpper().Contains(q.ToUpper()))
                )
                .OrderBy(r => r.Id);
            }
            var data = listData.Skip(fromIdx)
                .Take(toIdx)
                .Select(r => new { id = r.Id, text = r.Product_Name})
                .ToList();

            return Json(new { items = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BookList(string q, string initValue = "", int page = 0)
        {
            int fromIdx = page > 0 ? (page * 10) : 0;
            int toIdx = page > 0 ? page * 10 : 10;
            var listData = db.Books.Where(r => 1 == 2);

            if (!string.IsNullOrEmpty(initValue))
            {
                listData = db.Books
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(initValue) || (initValue == r.Id.ToString()))
                )
                .OrderBy(r => r.Id);
            }
            else
            {
                listData = db.Books
                .Where
                (
                    r =>
                    (string.IsNullOrEmpty(q) || (r.Book_Name).ToUpper().Contains(q.ToUpper()))
                )
                .OrderBy(r => r.Id);
            }
            var data = listData.Skip(fromIdx)
                .Take(toIdx)
                .Select(r => new { id = r.Id, text = r.Book_Name })
                .ToList();

            return Json(new { items = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetProductData(long Id)
        {
            var product = db.Products.Where(r => r.Id == Id).Select(r => new { Product_UOM = r.Product_UOM }).FirstOrDefault();
            return Json(product, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCustomerData(long Id)
        {
            var customer = db.Customers.Where(r => r.Id == Id).Select(r => new { Address = r.Address }).FirstOrDefault();
            return Json(customer, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetBookData(long Id)
        {
            var book = db.Books.Where(r => r.Id == Id).Select(r => new { Authors = r.Authors }).FirstOrDefault();
            return Json(book, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectBase/Controllers/UserController.cs
using ProjectBase.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectBase.Controllers
{
    public class UserController : Controller
    {
        ProjectBaseEntities db = new ProjectBaseEntities();

        [CustomAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadData(string draw = null, string start = null, string length = null, OrderClass[] order = null, ColumnClass[] columns = null, string[] filter = null)
        {
            try
            {
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int filteredTotal = 0, recordsTotal = 0;
                string orderBy = string.Join(",", order.Select(r => ("A." + columns[r.column].data + " " + r.dir)));
                orderBy = orderBy.Replace("A.Group_Code", "A.Group_Code");
                string query = @"
                    SELECT A.*
                    FROM [User] A
                    WHERE 1=1 {0}
                    ORDER BY {3} {2} {1}
                ", whereQuery = "",
                queryCount = @"SELECT COUNT(A.Id) AS Count_ FROM [User] A WHERE 1=1 {0}";

                List<SqlParameter> parameters = new List<SqlParameter>();
                if (filter != null && filter.Length > 0)
                {
                    for (int i = 0; i < filter.Length; i++)
                    {
                        if (string.IsNullOrEmpty(filter[i]))
                            continue;
                        string columnName = columns[i].data;
                        string tableAlias = "A.";
                        if (columnName == "Process_Group_Code")
                            tableAlias = "B.";
                        else if (columnName == "Location_Code")
                            tableAlias = "C.";

                        whereQuery += " AND " + tableAlias + columnName + " LIKE @" + columnName;
                        parameters.Add(new SqlParameter("@" + columnName, "%" + filter[i] + "%"));
                    }
                }

                List<SqlParameter> parameterc = new List<SqlParameter>();
                foreach (SqlParameter prm in parameters)
                    parameterc.Add(new SqlParameter(prm.ParameterName, prm.Value));

                List<UserViewModel> listOfData_ =
                    db.Database.SqlQuery<UserViewModel>(string.Format(query, whereQuery, (pageSize > 0 ? "FETCH NEXT " + pageSize.ToString() + " ROWS ONLY" : ""), (skip > -1 ? "OFFSET " + skip.ToString() + " ROWS" : ""), (string.IsNullOrEmpty(orderBy) ? "Create_Date DESC" : orderBy)), parameters.ToArray())
                    .ToList();

                var qc = db.Database.SqlQuery<Int32>(string.Format(queryCount, whereQuery), parameterc.ToArray()).ToArray();
                filteredTotal = qc.Length > 0 ? qc[0] : 0;

                var qt = db.Database.SqlQuery<Int32>(string.Format(queryCount, "")).ToArray();
                recordsTotal = qt.Length > 0 ? qt[0] : 0;

                return Json(new { draw = draw, recordsFiltered = filteredTotal, recordsTotal = recordsTotal, data = listOfData_ });
            }
            catch (Exception exc)
            {
                var a = exc.Message;
                throw;
            }
        }

        [CustomAuthorize]
        public ActionResult Editor(string mode, long? Id)
        {
            UserViewModel viewModel = new UserViewModel();
            if (mode != Constants.FORM_MODE_CREATE && Id != null)
                viewModel = new UserViewModel(db, Id.Value);
            else if (mode != Constants.FORM_MODE_CREATE && Id == null)
                return RedirectToAction("Index");
            viewModel.mode = mode;
            return View("Editor", viewModel);
        }

        [HttpPost]
        public ActionResult Editor(UserViewModel viewModel)
        {
            var a = ModelState.AsEnumerable().Where(r => r.Value.Errors.Count > 0).ToList();
            if (ModelState.IsValid)
            {
                viewModel.Save(db);
                if (viewModel.result == Constants.OK)
                    return RedirectToAction("Index");
                else
                {
                    ModelState.AddModelError(Constants._ERROR, viewModel.result);
                }
            }
            else
            {
                ModelState.AddModelError(Constants._ERROR, string.Join(",", (ModelState.Values.Where(r => r.Errors.Count > 0).SelectMany(r => r.Errors).Select(r => r.ErrorMessage).ToArray())) + "<br/>");
            }
            return View("Editor", viewModel);
        }
    }
}

ProjectBase/Views/User/Editor.cshtml
@using ProjectBase.Utilities;
@model ProjectBase.ViewModels.UserViewModel

@{
    ViewBag.Title = "[" + Model.mode + "] User";
    var mode = Request.QueryString["mode"];

}

<style type="text/css">
    td > .two-decimals, .four-decimals {
        min-width: 70px !important;
    }

    th {
        vertical-align: middle;
        text-align: center;
    }

    td {
        vertical-align: middle;
        text-align: center;
        padding: 0px !important;
    }

        td > .form-control {
            border-color: transparent;
        }
</style>
<section class="content-header">
    <h1>
        @Model.mode
        <small>User</small>
    </h1>
    <ol class="breadcrumb">
        <li><a><i class="fa fa-dashboard"></i> Master Data > Users</a></li>
        <li class="active">User</li>
    </ol>
</section>
@using (Html.BeginForm("Editor", "User", new { Id = Request.QueryString["Id"], mode = mode}, FormMethod.Post, new { id = "EditorForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <section class="col-md-6 connectedSortable ui-sortable">
            <div class="box box-danger">
                <div class="box-header ui-sortable-handle">
                    <i class="ion ion-bookmark"></i>
                    <h3 class="box-title">Header</h3>
                </div>
                <div class="box-body">
                    <div class="form-horizontal">
                        @Html.ValidationMessage(Constants._ERROR, new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.mode)
                        @Html.HiddenFor(model => model.result)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Employee_Number, htmlAttributes: new { @class = "control-label col-sm-4" })
                            <div class="col-sm-8">
                                @Html.EditorFor(model => model.Employee_Number, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Employee_Number, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Full_Name, htmlAttributes: new { @class = "control-label col-sm-4" })
                            <div class="col-sm-8">
                                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-sm-4" })
                            <div class="col-sm-8">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                </div>
                <div class="box-footer clearfix no-border">
                    <div class="row pull-right">
                        <div class="col-md-6">
                            <a href="@Url.Action("Index")" class="btn btn-sm btn-default btn-flat"><i class="fa fa-arrow-left"></i> Back</a>
                        </div>
                        <div class="col-md-6">
                            @{
                                if (mode == @Constants.FORM_MODE_CREATE)
                                {
                                    <button id="submit_" type="button" class="btn btn-sm btn-success btn-flat">
                                        <span class="fa fa-floppy-o"></span> <b>Save</b>
                                    </button>
                                }
                                else if (mode == @Constants.FORM_MODE_DELETE)
                                {
                                    <button id="submit_" type="button" class="btn btn-sm btn-danger btn-flat">
                                        <span class="fa fa-trash"></span> <b>Delete</b>
                                    </button>
                                }
                                else if (mode == @Constants.FORM_MODE_EDIT)
                                {
                                    <button id="submit_" type="button" class="btn btn-sm btn-success btn-flat">
                                        <span class="fa fa-edit"></span> <b>Edit</b>
                                    </button>
                                }
                            }

                            @*<a href="#" class="btn btn-success" id="btn-save-all" onclick="document.getElementById('EditorForm').submit();"><i class="fa fa-floppy-o"></i> Save</a>*@
                            <input id="submit" type="submit" style="display:none" />
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="col-md-6 connectedSortable ui-sortable">
            <div class="box box-info">
                <div class="box-header ui-sortable-handle">
                    <i class="ion ion-clipboard"></i>
                    <h3 class="box-title">Details</h3>
                </div>
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table-condensed table-bordered table-striped" id="table_detail" style="width:100%">
                            <thead>
                                <tr>
                                    <th>
                                        <button type="button" id="btn-add-detail" class="btn btn-xs btn-sm btn-success btn-flat"><i class="fa fa-plus"></i></button>
                                    </th>
                                    <th>Group</th>
                                </tr>
                            </thead>
                            <tbody id="tbody_detail">
                                <tr class="tr-blueprint" style="display:none">
                                    <td>
                                        <button type="button" class="btn btn-xs btn-sm btn-danger btn-flat btn-del-detail"><i class="fa fa-minus"></i></button>
                                        <input type="hidden" name="Id" value="0" />
                                        <input type="hidden" name="User_Id" value="0" />

                                        <input type="hidden" name="mode" value="@Constants.FORM_MODE_CREATE" />
                                    </td>
                                    <td>
                                        <input type="text" name="Group_Id" class="form-control" />
                                    </td>
                                </tr>
                                @{
                                    if (Model != null && Model.Details != null && Model.Details.Count > 0)
                                    {
                                        for (int i = 0; i < Model.Details.Count; i++)
                                        {
                                            var Detail = Model.Details[i];
                                            <tr>
                                                <td>
                                                    <button type="button" class="btn btn-xs btn-sm btn-danger btn-flat btn-del-detail"><i class="fa fa-minus"></i></button>
                                                    <input type="hidden" name="Details[@i.ToString()].Id" value="@Detail.Id" />
                                                    <input type="hidden" name="Details[@i.ToString()].User_Id" value="@Detail.User_Id" />
                                                    <input type="hidden" name="Details[@i.ToString()].mode" value="@Detail.mode" />
                                                </td>
                                                <td>
                                                    <input type="text" name="Details[@i.ToString()].Group_Id" class="form-control" value="@(Detail.Group_Id)" />
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="box-footer clearfix no-border">
                </div>
            </div>
        </section>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#tbody_detail tr:not(.tr-blueprint)").each(function (i) {
                var menuId = $("input[name$='.Group_Id']", $(this));

                InitAjaxSelect2(menuId, '@Url.Action("GroupList", "Ajax")', function () { return {} }, -1);

            });

            $("#btn-add-detail").click(function () {
                var tbl = $(this).closest("table");
                var blueprint = tbl.find(".tr-blueprint").first().clone();
                var rowCount = $("#tbody_detail tr:not(.tr-blueprint)").length;
                blueprint.appendTo(tbl).removeClass("tr-blueprint").show();
                var tableName = "Details[" + rowCount + "].";
                $("input[type=text]", blueprint).each(function () {
                    var name = $(this).prop('name');

                    $(this).prop('name', tableName + $(this).prop('name'));

                    if (name == "Group_Id") InitAjaxSelect2($(this), '@Url.Action("GroupList", "Ajax")', function () { return { } }, -1);
                });

                $("input[type=checkbox]", blueprint).each(function () {
                    var name = $(this).prop('name');

                    $(this).prop('name', tableName + $(this).prop('name'));

                    $(this).change(function () {
                        if ($(this).prop("checked")) $(this).val(true);
                        else $(this).val(false);
                    });
                });

                $("input[type=hidden]", blueprint).each(function () {
                    $(this).prop('name', tableName + $(this).prop('name'));
                });

                $("textarea", blueprint).each(function () {
                    $(this).prop('name', tableName + $(this).prop('name'));
                });
                $(".btn-del-detail", blueprint).click(function () {
                    var row = $(this).closest("tr");
                    var td = $(row).find('td');

                    var detailMode = $("[name$='.mode']", $(row)).val();
                    if (detailMode == '@Constants.FORM_MODE_CREATE')
                        row.remove();
                    else {
                        $("[name$='.mode']", $(row)).val('@Constants.FORM_MODE_DELETE');
                        $(row).attr('style', 'display:none');
                    }
                });
                reInitInputs();
            });

            $(".btn-del-detail").click(function () {
                var row = $(this).closest("tr");

                //$ = Ends with, * = Contains, ^ - Starts with
                var detailMode = $("input[name$='.mode']", $(row)).val();
                if (detailMode == '@Constants.FORM_MODE_CREATE')
                    row.remove();
                else {
                    $("[name$='.mode']", $(row)).val('@Constants.FORM_MODE_DELETE');
                    $(row).attr('style', 'display:none');
                }
            });

            $('#tbody_detail tr:not(.tr-blueprint) input, textarea').on('change', function () {
                var tr = this.closest('tr');
                var x = $("[name$='.mode']", $(tr)).val();
                if (x == '@Constants.FORM_MODE_UNCHANGED')
                    $("[name$='.mode']", $(tr)).val('@Constants.FORM_MODE_EDIT');
            });

             if ($("#mode").val() == '@Constants.FORM_MODE_VIEW') {
                $("#EditorForm :input").attr("disabled", true);
                $("button").attr('disabled', true);
                $("#submit").attr("disabled", true);
                $("#submit_").attr("disabled", true);
            }
            else if ($("#mode").val() == '@Constants.FORM_MODE_DELETE') {
                $("#EditorForm :input").not("#submit_, #submit").attr("readonly", true);
             //   $(".select2").attr("disabled", true);
              //  $("button").attr('disabled', true);
                $("#submit_").val('Delete');
            }

            $("#submit_").click(function () {
                bootbox.confirm({
                    message: "Are you sure?",
                    buttons: {
                        confirm: {
                            label: 'Yes',
                            className: 'btn-success btn-primary'
                        },
                        cancel: {
                            label: 'No',
                            className: 'btn-danger'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            $("#submit").click();
                        }
                    }
                });
            });
        });
    </script>
}